-- ==================================================================
-- NearX Product Catalog Seed — 100+ Packaged & General Use Products
-- Run this in Supabase SQL Editor AFTER schema is set up.
-- Uses the dummy store: 'ssssssss-ssss-ssss-ssss-ssssssssssss'
-- ==================================================================

-- Clear existing seed products (optional — keeps store-owner-added products intact)
DELETE FROM products WHERE store_id = 'ssssssss-ssss-ssss-ssss-ssssssssssss';

INSERT INTO products (store_id, name, brand, category, description, image_url, mrp, discount_percent, sale_price, stock, expiry_date) VALUES

-- ============== DAIRY (12 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Amul Taaza Toned Milk 1L', 'Amul', 'Dairy', 'Toned milk with 3% fat, ideal for daily use', 'https://www.bigbasket.com/media/uploads/p/l/40199301_1-amul-taaza-toned-fresh-milk.jpg', 5400, 40, 3240, 25, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Mother Dairy Classic Curd 400g', 'Mother Dairy', 'Dairy', 'Thick and creamy set curd', 'https://www.bigbasket.com/media/uploads/p/l/241014_9-mother-dairy-classic-curd.jpg', 3500, 35, 2275, 18, CURRENT_DATE + INTERVAL '4 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Amul Cheese Slices 200g', 'Amul', 'Dairy', 'Processed cheese slices, pack of 10', 'https://www.bigbasket.com/media/uploads/p/l/265061_8-amul-cheese-slices.jpg', 11500, 25, 8625, 15, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Nestle A+ Slim Milk 1L', 'Nestle', 'Dairy', 'Double toned slim milk', 'https://www.bigbasket.com/media/uploads/p/l/40018414_3-nestle-a-slim-milk.jpg', 5600, 45, 3080, 20, CURRENT_DATE + INTERVAL '2 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Amul Butter 500g', 'Amul', 'Dairy', 'Pasteurised table butter', 'https://www.bigbasket.com/media/uploads/p/l/126906_10-amul-pasteurised-butter.jpg', 27500, 20, 22000, 12, CURRENT_DATE + INTERVAL '15 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Cream Cheese Spread 180g', 'Britannia', 'Dairy', 'Smooth and creamy cheese spread', 'https://www.bigbasket.com/media/uploads/p/l/40032041_2-britannia-cheese-spread-premium.jpg', 9900, 30, 6930, 10, CURRENT_DATE + INTERVAL '8 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Epigamia Greek Yogurt Strawberry 90g', 'Epigamia', 'Dairy', 'High protein Greek yogurt', 'https://www.bigbasket.com/media/uploads/p/l/40101382_4-epigamia-greek-yogurt-strawberry.jpg', 5000, 50, 2500, 14, CURRENT_DATE + INTERVAL '5 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Amul Masti Buttermilk 200ml', 'Amul', 'Dairy', 'Spiced buttermilk tetra pack', 'https://www.bigbasket.com/media/uploads/p/l/265799_7-amul-masti-spiced-buttermilk.jpg', 2000, 40, 1200, 30, CURRENT_DATE + INTERVAL '6 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Milky Mist Paneer 200g', 'Milky Mist', 'Dairy', 'Fresh cottage cheese block', 'https://www.bigbasket.com/media/uploads/p/l/40024886_3-milky-mist-premium-paneer.jpg', 9000, 35, 5850, 8, CURRENT_DATE + INTERVAL '4 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Amul Gold Full Cream Milk 1L', 'Amul', 'Dairy', 'Full cream standardised milk', 'https://www.bigbasket.com/media/uploads/p/l/40199305_3-amul-gold-full-cream-fresh-milk.jpg', 6800, 30, 4760, 22, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Nestle Milkmaid 400g', 'Nestle', 'Dairy', 'Sweetened condensed milk', 'https://www.bigbasket.com/media/uploads/p/l/270038_8-nestle-milkmaid-sweetened-condensed-milk.jpg', 16500, 15, 14025, 16, CURRENT_DATE + INTERVAL '25 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Go Cheese Grated Mozzarella 250g', 'Go', 'Dairy', 'Pizza-ready shredded mozzarella', 'https://www.bigbasket.com/media/uploads/p/l/40182753_1-go-cheese-shredded-mozzarella.jpg', 17000, 25, 12750, 9, CURRENT_DATE + INTERVAL '10 days'),

-- ============== SNACKS (15 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Lays Classic Salted Chips 52g', 'Lays', 'Snacks', 'Crispy potato chips', 'https://www.bigbasket.com/media/uploads/p/l/241600_8-lays-potato-chips-classic-salted.jpg', 2000, 50, 1000, 40, CURRENT_DATE + INTERVAL '5 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Kurkure Masala Munch 94g', 'Kurkure', 'Snacks', 'Crunchy corn puffs with masala', 'https://www.bigbasket.com/media/uploads/p/l/266184_6-kurkure-namkeen-masala-munch.jpg', 2000, 40, 1200, 35, CURRENT_DATE + INTERVAL '7 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Parle-G Gold Biscuits 100g', 'Parle', 'Snacks', 'Premium glucose biscuits', 'https://www.bigbasket.com/media/uploads/p/l/40020062_2-parle-g-gold-biscuit.jpg', 2500, 30, 1750, 50, CURRENT_DATE + INTERVAL '14 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Good Day Butter Cookies 250g', 'Britannia', 'Snacks', 'Rich buttery cookies', 'https://www.bigbasket.com/media/uploads/p/l/40193638_4-britannia-good-day-cashew-cookies.jpg', 4000, 25, 3000, 28, CURRENT_DATE + INTERVAL '18 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Haldirams Aloo Bhujia 200g', 'Haldirams', 'Snacks', 'Classic spiced potato sev', 'https://www.bigbasket.com/media/uploads/p/l/40017736_2-haldirams-namkeen-aloo-bhujia.jpg', 6500, 35, 4225, 20, CURRENT_DATE + INTERVAL '10 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Oreo Original Cream Biscuit 120g', 'Cadbury', 'Snacks', 'Chocolate sandwich cookies with cream', 'https://www.bigbasket.com/media/uploads/p/l/40026634_3-cadbury-oreo-vanilla-creme-biscuit.jpg', 3000, 40, 1800, 32, CURRENT_DATE + INTERVAL '6 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Bingo Mad Angles Achari Masti 72g', 'Bingo', 'Snacks', 'Triangle-shaped tangy snack', 'https://www.bigbasket.com/media/uploads/p/l/40021060_5-bingo-mad-angles-achari-masti.jpg', 2000, 45, 1100, 25, CURRENT_DATE + INTERVAL '4 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Cadbury 5 Star Chocolate Bar 40g (Pack of 5)', 'Cadbury', 'Snacks', 'Caramel nougat chocolate bar', 'https://www.bigbasket.com/media/uploads/p/l/40247792-2_1-cadbury-5-star-chocolate-bar.jpg', 10000, 20, 8000, 18, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Pringles Original 107g', 'Pringles', 'Snacks', 'Stackable potato crisps', 'https://www.bigbasket.com/media/uploads/p/l/40089812_4-pringles-potato-chips-original.jpg', 14900, 30, 10430, 12, CURRENT_DATE + INTERVAL '9 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Sunfeast Dark Fantasy Choco Fills 75g', 'Sunfeast', 'Snacks', 'Cookies with rich choco cream filling', 'https://www.bigbasket.com/media/uploads/p/l/40022036_5-sunfeast-dark-fantasy-choco-fills.jpg', 4000, 35, 2600, 22, CURRENT_DATE + INTERVAL '11 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Bikano Rasgulla Tin 1kg', 'Bikano', 'Snacks', 'Ready-to-eat rasgulla sweets', 'https://www.bigbasket.com/media/uploads/p/l/40135534_3-bikano-rasgulla-tin.jpg', 22000, 25, 16500, 6, CURRENT_DATE + INTERVAL '8 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Act II Classic Salted Popcorn 30g', 'Act II', 'Snacks', 'Ready-to-eat popcorn', 'https://www.bigbasket.com/media/uploads/p/l/40024449_4-act-ii-rte-popcorn-classic-salted.jpg', 2000, 40, 1200, 38, CURRENT_DATE + INTERVAL '5 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'McVities Digestive Biscuits 250g', 'McVities', 'Snacks', 'Whole wheat digestive biscuits', 'https://www.bigbasket.com/media/uploads/p/l/265841_7-mcvities-digestive-biscuit.jpg', 8500, 20, 6800, 15, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Cadbury Dairy Milk Silk 150g', 'Cadbury', 'Snacks', 'Smooth and creamy milk chocolate', 'https://www.bigbasket.com/media/uploads/p/l/40000195_8-cadbury-dairy-milk-silk-chocolate-bar.jpg', 16000, 15, 13600, 10, CURRENT_DATE + INTERVAL '28 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Too Yumm Multigrain Chips 54g', 'Too Yumm', 'Snacks', 'Baked not fried multigrain chips', 'https://www.bigbasket.com/media/uploads/p/l/40126416_3-too-yumm-multigrain-chips-chinese-hot-chilli.jpg', 2000, 50, 1000, 28, CURRENT_DATE + INTERVAL '3 days'),

-- ============== BEVERAGES (14 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Tropicana Orange Juice 1L', 'Tropicana', 'Beverages', '100% orange juice not from concentrate', 'https://www.bigbasket.com/media/uploads/p/l/251006_13-tropicana-100-juice-orange.jpg', 11000, 50, 5500, 15, CURRENT_DATE + INTERVAL '5 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Real Fruit Power Mixed Fruit 1L', 'Real', 'Beverages', 'Mixed fruit juice drink', 'https://www.bigbasket.com/media/uploads/p/l/265524_8-real-fruit-power-juice-mixed-fruit.jpg', 10000, 40, 6000, 12, CURRENT_DATE + INTERVAL '7 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Coca-Cola 750ml', 'Coca-Cola', 'Beverages', 'Classic cola carbonated drink', 'https://www.bigbasket.com/media/uploads/p/l/251011_10-coca-cola-soft-drink.jpg', 3800, 25, 2850, 30, CURRENT_DATE + INTERVAL '15 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Sprite Lemon-Lime 750ml', 'Sprite', 'Beverages', 'Clear lemon-lime soda', 'https://www.bigbasket.com/media/uploads/p/l/264041_10-sprite-soft-drink.jpg', 3800, 25, 2850, 28, CURRENT_DATE + INTERVAL '14 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Bisleri Water 1L (Pack of 12)', 'Bisleri', 'Beverages', 'Packaged drinking water', 'https://www.bigbasket.com/media/uploads/p/l/100011538_3-bisleri-mineral-water.jpg', 24000, 10, 21600, 40, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Red Bull Energy Drink 250ml', 'Red Bull', 'Beverages', 'Energy drink with caffeine and taurine', 'https://www.bigbasket.com/media/uploads/p/l/264848_7-red-bull-energy-drink.jpg', 11500, 20, 9200, 10, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Appy Fizz Apple Sparkling Drink 250ml', 'Appy', 'Beverages', 'Sparkling apple juice drink', 'https://www.bigbasket.com/media/uploads/p/l/40119416_2-appy-fizz-sparkling-apple-juice-drink.jpg', 3000, 35, 1950, 22, CURRENT_DATE + INTERVAL '6 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Maaza Mango Drink 600ml', 'Maaza', 'Beverages', 'Mango pulp juice drink', 'https://www.bigbasket.com/media/uploads/p/l/265561_6-maaza-mango-drink.jpg', 3500, 40, 2100, 18, CURRENT_DATE + INTERVAL '4 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Paper Boat Aam Panna 200ml', 'Paper Boat', 'Beverages', 'Traditional raw mango drink', 'https://www.bigbasket.com/media/uploads/p/l/40022012_5-paper-boat-aam-panna.jpg', 3000, 45, 1650, 20, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Nescafe Ready to Drink Latte 180ml', 'Nescafe', 'Beverages', 'Chilled coffee latte can', 'https://www.bigbasket.com/media/uploads/p/l/40182758_2-nescafe-ready-to-drink-latte.jpg', 5000, 30, 3500, 14, CURRENT_DATE + INTERVAL '10 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Frooti Mango 1.2L', 'Frooti', 'Beverages', 'Mango fruit drink', 'https://www.bigbasket.com/media/uploads/p/l/264634_4-frooti-mango-drink-fresh-juicy.jpg', 6000, 35, 3900, 16, CURRENT_DATE + INTERVAL '8 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Tang Orange 500g', 'Tang', 'Beverages', 'Instant orange drink powder', 'https://www.bigbasket.com/media/uploads/p/l/266248_5-tang-instant-drink-mix-orange.jpg', 16000, 20, 12800, 11, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dabur Real Litchi Juice 1L', 'Dabur', 'Beverages', 'Litchi flavoured fruit nectar', 'https://www.bigbasket.com/media/uploads/p/l/265529_8-real-fruit-power-juice-litchi.jpg', 10000, 40, 6000, 13, CURRENT_DATE + INTERVAL '6 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Tetley Green Tea Lemon 25 Bags', 'Tetley', 'Beverages', 'Green tea bags with lemon flavour', 'https://www.bigbasket.com/media/uploads/p/l/40029701_3-tetley-green-tea-lemon.jpg', 15000, 15, 12750, 20, CURRENT_DATE + INTERVAL '28 days'),

-- ============== BAKERY (10 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Whole Wheat Bread 400g', 'Britannia', 'Bakery', '100% whole wheat sandwich bread', 'https://www.bigbasket.com/media/uploads/p/l/40023251_2-britannia-100-whole-wheat-bread.jpg', 4500, 40, 2700, 15, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Modern White Bread 400g', 'Modern', 'Bakery', 'Soft white sandwich bread', 'https://www.bigbasket.com/media/uploads/p/l/241563_8-modern-white-bread.jpg', 4000, 50, 2000, 12, CURRENT_DATE + INTERVAL '2 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Fruit Cake 250g', 'Britannia', 'Bakery', 'Soft sponge cake with dried fruits', 'https://www.bigbasket.com/media/uploads/p/l/40041816_2-britannia-cake-fruity.jpg', 8500, 30, 5950, 8, CURRENT_DATE + INTERVAL '8 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'English Oven Burger Buns (Pack of 4)', 'English Oven', 'Bakery', 'Soft sesame burger buns', 'https://www.bigbasket.com/media/uploads/p/l/40036937_3-english-oven-burger-buns.jpg', 7500, 35, 4875, 10, CURRENT_DATE + INTERVAL '4 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Milk Rusk 230g', 'Britannia', 'Bakery', 'Crispy oven-baked milk rusk', 'https://www.bigbasket.com/media/uploads/p/l/40017457_5-britannia-toastea-premium-bake-rusk-milk.jpg', 3800, 25, 2850, 18, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'English Oven Hotdog Rolls (Pack of 4)', 'English Oven', 'Bakery', 'Soft hotdog bread rolls', 'https://www.bigbasket.com/media/uploads/p/l/40127135_2-english-oven-premium-hot-dog-rolls.jpg', 7000, 40, 4200, 8, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Britannia Cheese Garlic Bread 120g', 'Britannia', 'Bakery', 'Garlic bread with cheese filling', 'https://www.bigbasket.com/media/uploads/p/l/40248696_1-britannia-cheese-garlic-bread-with-cheese.jpg', 5000, 45, 2750, 7, CURRENT_DATE + INTERVAL '2 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Pillsbury Cookie Cake Chocolate 23g (Pack of 6)', 'Pillsbury', 'Bakery', 'Soft baked chocolate cookie cakes', 'https://www.bigbasket.com/media/uploads/p/l/40062576_2-pillsbury-cookie-cake-chocolate.jpg', 6000, 30, 4200, 20, CURRENT_DATE + INTERVAL '15 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Harvest Gold Multigrain Bread 450g', 'Harvest Gold', 'Bakery', 'Multi-seed multigrain bread', 'https://www.bigbasket.com/media/uploads/p/l/40037453_5-harvest-gold-hearty-brown-bread.jpg', 5500, 40, 3300, 9, CURRENT_DATE + INTERVAL '3 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Monginis Chocolate Pastry (Pack of 2)', 'Monginis', 'Bakery', 'Fresh chocolate cream pastries', 'https://www.bigbasket.com/media/uploads/p/l/40132652_1-monginis-pastry-chocolate.jpg', 12000, 50, 6000, 5, CURRENT_DATE + INTERVAL '1 days'),

-- ============== PANTRY (18 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Maggi 2-Minute Noodles (Pack of 12)', 'Maggi', 'Pantry', 'Masala flavour instant noodles', 'https://www.bigbasket.com/media/uploads/p/l/266164_7-maggi-2-minute-instant-noodles-masala.jpg', 16800, 15, 14280, 35, CURRENT_DATE + INTERVAL '25 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Saffola Gold Oil 1L', 'Saffola', 'Pantry', 'Blended edible vegetable oil', 'https://www.bigbasket.com/media/uploads/p/l/147491_5-saffola-gold-pro-healthy-lifestyle-edible-oil.jpg', 18900, 10, 17010, 12, CURRENT_DATE + INTERVAL '28 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Aashirvaad Atta 5kg', 'Aashirvaad', 'Pantry', 'Whole wheat flour for chapati', 'https://www.bigbasket.com/media/uploads/p/l/126905_6-aashirvaad-atta-whole-wheat.jpg', 29000, 10, 26100, 15, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Tata Salt 1kg', 'Tata', 'Pantry', 'Iodised vacuum evaporated salt', 'https://www.bigbasket.com/media/uploads/p/l/274020_3-tata-salt.jpg', 2800, 15, 2380, 50, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'MDH Garam Masala 100g', 'MDH', 'Pantry', 'Blend of aromatic spices', 'https://www.bigbasket.com/media/uploads/p/l/40000197_3-mdh-masala-garam.jpg', 8500, 20, 6800, 18, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Kissan Mixed Fruit Jam 500g', 'Kissan', 'Pantry', 'Real fruit jam spread', 'https://www.bigbasket.com/media/uploads/p/l/264928_4-kissan-mixed-fruit-jam.jpg', 13500, 25, 10125, 14, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Maggi Hot & Sweet Tomato Chilli Sauce 1kg', 'Maggi', 'Pantry', 'Tomato ketchup with chilli', 'https://www.bigbasket.com/media/uploads/p/l/265926_3-maggi-hot-sweet-tomato-chilli-sauce-bottle.jpg', 18000, 20, 14400, 10, CURRENT_DATE + INTERVAL '18 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Saffola Oats 1kg', 'Saffola', 'Pantry', 'Rolled oats for healthy breakfast', 'https://www.bigbasket.com/media/uploads/p/l/40022438_3-saffola-oats-natural.jpg', 15500, 25, 11625, 16, CURRENT_DATE + INTERVAL '15 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Sundrop Peanut Butter Creamy 462g', 'Sundrop', 'Pantry', 'Smooth creamy peanut butter', 'https://www.bigbasket.com/media/uploads/p/l/40069997_6-sundrop-peanut-butter-creamy.jpg', 22000, 30, 15400, 8, CURRENT_DATE + INTERVAL '10 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Quaker Oats 1kg', 'Quaker', 'Pantry', 'Rolled oats rich in fiber', 'https://www.bigbasket.com/media/uploads/p/l/40014044_3-quaker-oats.jpg', 16000, 20, 12800, 20, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Kelloggs Corn Flakes 475g', 'Kelloggs', 'Pantry', 'Crispy corn flakes breakfast cereal', 'https://www.bigbasket.com/media/uploads/p/l/229651_10-kelloggs-corn-flakes-original.jpg', 19500, 25, 14625, 14, CURRENT_DATE + INTERVAL '16 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Kelloggs Chocos 375g', 'Kelloggs', 'Pantry', 'Chocolatey breakfast cereal for kids', 'https://www.bigbasket.com/media/uploads/p/l/229655_8-kelloggs-chocos-chocolate-breakfast-cereal.jpg', 19000, 30, 13300, 12, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'MTR Ready To Eat Poha 180g', 'MTR', 'Pantry', 'Instant poha just heat and eat', 'https://www.bigbasket.com/media/uploads/p/l/40028037_4-mtr-ready-to-eat-poha.jpg', 5500, 35, 3575, 18, CURRENT_DATE + INTERVAL '8 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'MTR Ready To Eat Upma 180g', 'MTR', 'Pantry', 'Instant rava upma heat and eat', 'https://www.bigbasket.com/media/uploads/p/l/40028029_4-mtr-ready-to-eat-upma.jpg', 5500, 35, 3575, 16, CURRENT_DATE + INTERVAL '7 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dabur Honey 500g', 'Dabur', 'Pantry', '100% pure natural honey', 'https://www.bigbasket.com/media/uploads/p/l/265515_8-dabur-honey-100-pure-world-s-no1-honey-brand.jpg', 27000, 15, 22950, 10, CURRENT_DATE + INTERVAL '26 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Nutella Hazelnut Spread 350g', 'Nutella', 'Pantry', 'Hazelnut cocoa spread', 'https://www.bigbasket.com/media/uploads/p/l/40079309_4-nutella-hazelnut-spread-with-cocoa.jpg', 39900, 20, 31920, 6, CURRENT_DATE + INTERVAL '18 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Bambino Vermicelli 850g', 'Bambino', 'Pantry', 'Roasted vermicelli for upma and payasam', 'https://www.bigbasket.com/media/uploads/p/l/266547_5-bambino-premium-roasted-vermicelli.jpg', 9000, 20, 7200, 22, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dettol Instant Hand Sanitizer 200ml', 'Dettol', 'Pantry', 'Kills 99.9% germs instantly', 'https://www.bigbasket.com/media/uploads/p/l/40000614_5-dettol-instant-hand-sanitizer.jpg', 10000, 40, 6000, 15, CURRENT_DATE + INTERVAL '6 days'),

-- ============== CLEANING (12 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Vim Dishwash Gel Lemon 750ml', 'Vim', 'Cleaning', 'Liquid dish wash with lemon', 'https://www.bigbasket.com/media/uploads/p/l/241107_9-vim-dishwash-gel-lemon.jpg', 14000, 25, 10500, 18, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Surf Excel Easy Wash 1.5kg', 'Surf Excel', 'Cleaning', 'Detergent powder for washing machines', 'https://www.bigbasket.com/media/uploads/p/l/40025055_2-surf-excel-easy-wash-detergent-powder.jpg', 22000, 15, 18700, 12, CURRENT_DATE + INTERVAL '28 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Harpic Power Plus 500ml', 'Harpic', 'Cleaning', 'Toilet cleaning liquid', 'https://www.bigbasket.com/media/uploads/p/l/40025063_5-harpic-power-plus-toilet-cleaner.jpg', 9900, 20, 7920, 15, CURRENT_DATE + INTERVAL '25 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Lizol Disinfectant Floor Cleaner Citrus 500ml', 'Lizol', 'Cleaning', 'Surface disinfectant with citrus fragrance', 'https://www.bigbasket.com/media/uploads/p/l/40025080_5-lizol-disinfectant-surface-floor-cleaner-citrus.jpg', 11000, 20, 8800, 14, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Scotch-Brite Scrub Pad (Pack of 3)', 'Scotch-Brite', 'Cleaning', 'Heavy-duty scrub sponge pads', 'https://www.bigbasket.com/media/uploads/p/l/40025090_2-scotch-brite-scrub-pad.jpg', 5000, 15, 4250, 25, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Colin Glass Cleaner 500ml', 'Colin', 'Cleaning', 'Spray cleaner for glass surfaces', 'https://www.bigbasket.com/media/uploads/p/l/40025106_1-colin-glass-surface-cleaner-liquid-spray.jpg', 12000, 20, 9600, 10, CURRENT_DATE + INTERVAL '24 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Pril Dishwash Liquid 425ml', 'Pril', 'Cleaning', 'Concentrated dish wash gel', 'https://www.bigbasket.com/media/uploads/p/l/40058027_2-pril-dishwash-speckles-liquid-gel-lime.jpg', 10000, 25, 7500, 16, CURRENT_DATE + INTERVAL '18 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Domex Fresh Guard Disinfectant Toilet Cleaner 500ml', 'Domex', 'Cleaning', 'Kills all germs in toilet', 'https://www.bigbasket.com/media/uploads/p/l/40020024_4-domex-fresh-guard-disinfectant-toilet-cleaner.jpg', 8500, 30, 5950, 14, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Odo Mos Mosquito Repellent Spray 100ml', 'Odo Mos', 'Cleaning', 'Personal mosquito repellent spray', 'https://www.bigbasket.com/media/uploads/p/l/40098020_2-odomos-mosquito-repellent-spray.jpg', 7000, 25, 5250, 20, CURRENT_DATE + INTERVAL '16 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Good Knight Gold Flash 45ml', 'Good Knight', 'Cleaning', 'Mosquito repellent liquid vaporizer refill', 'https://www.bigbasket.com/media/uploads/p/l/264637_5-good-knight-gold-flash-liquid-vapouriser.jpg', 7500, 20, 6000, 22, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Comfort After Wash Fabric Conditioner 860ml', 'Comfort', 'Cleaning', 'Fabric softener for fresh clothes', 'https://www.bigbasket.com/media/uploads/p/l/40025050_2-comfort-after-wash-morning-fresh-fabric-conditioner.jpg', 21000, 20, 16800, 8, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dettol Antiseptic Liquid 250ml', 'Dettol', 'Cleaning', 'Multi-purpose disinfectant liquid', 'https://www.bigbasket.com/media/uploads/p/l/264912_4-dettol-antiseptic-disinfectant-liquid.jpg', 11500, 15, 9775, 17, CURRENT_DATE + INTERVAL '26 days'),

-- ============== PERSONAL CARE (12 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Colgate Strong Teeth Toothpaste 200g', 'Colgate', 'Pantry', 'Calcium boost toothpaste', 'https://www.bigbasket.com/media/uploads/p/l/265584_3-colgate-toothpaste-strong-teeth.jpg', 9500, 20, 7600, 25, CURRENT_DATE + INTERVAL '28 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dettol Original Soap 125g (Pack of 4)', 'Dettol', 'Pantry', 'Antibacterial bathing soap', 'https://www.bigbasket.com/media/uploads/p/l/40025096_4-dettol-bathing-soap-original.jpg', 18000, 20, 14400, 15, CURRENT_DATE + INTERVAL '25 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Head & Shoulders Anti Dandruff Shampoo 340ml', 'Head & Shoulders', 'Pantry', 'Anti-dandruff shampoo', 'https://www.bigbasket.com/media/uploads/p/l/40025181_4-head-shoulders-anti-dandruff-shampoo.jpg', 33000, 15, 28050, 8, CURRENT_DATE + INTERVAL '24 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Dove Body Wash 250ml', 'Dove', 'Pantry', 'Nourishing body wash with moisturiser', 'https://www.bigbasket.com/media/uploads/p/l/40025059_1-dove-deeply-nourishing-body-wash.jpg', 22500, 20, 18000, 10, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Gillette Mach3 Razor Cartridge (Pack of 2)', 'Gillette', 'Pantry', 'Triple blade shaving cartridges', 'https://www.bigbasket.com/media/uploads/p/l/40025116_3-gillette-mach-3-manual-shaving-razor-blades-cartridge.jpg', 34000, 15, 28900, 6, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Nivea Body Lotion 400ml', 'Nivea', 'Pantry', 'Nourishing body lotion for dry skin', 'https://www.bigbasket.com/media/uploads/p/l/40025122_6-nivea-nourishing-body-milk-lotion.jpg', 32000, 20, 25600, 7, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Vaseline Body Lotion 400ml', 'Vaseline', 'Pantry', 'Intensive care cocoa glow body lotion', 'https://www.bigbasket.com/media/uploads/p/l/40025126_3-vaseline-intensive-care-body-lotion.jpg', 34500, 20, 27600, 9, CURRENT_DATE + INTERVAL '24 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Whisper Ultra Clean XL Wings Pads 30', 'Whisper', 'Pantry', 'Sanitary pads with wings for heavy flow', 'https://www.bigbasket.com/media/uploads/p/l/40025129_5-whisper-ultra-clean-sanitary-pads-xl-wings.jpg', 33000, 15, 28050, 12, CURRENT_DATE + INTERVAL '30 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Pepsodent Germicheck Toothpaste 200g', 'Pepsodent', 'Pantry', 'Cavity protection toothpaste', 'https://www.bigbasket.com/media/uploads/p/l/40025137_3-pepsodent-germicheck-toothpaste.jpg', 9000, 25, 6750, 20, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Listerine Cool Mint Mouthwash 250ml', 'Listerine', 'Pantry', 'Antiseptic mouthwash', 'https://www.bigbasket.com/media/uploads/p/l/40025142_4-listerine-cool-mint-mouthwash.jpg', 11000, 20, 8800, 14, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Parachute Coconut Oil 500ml', 'Parachute', 'Pantry', 'Pure pressed coconut oil for hair', 'https://www.bigbasket.com/media/uploads/p/l/40025148_4-parachute-100-pure-coconut-oil.jpg', 16000, 10, 14400, 18, CURRENT_DATE + INTERVAL '28 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Closeup Everfresh Toothpaste 150g', 'Closeup', 'Pantry', 'Gel toothpaste with mouthwash', 'https://www.bigbasket.com/media/uploads/p/l/40025152_3-closeup-ever-fresh-red-hot-gel-toothpaste.jpg', 9500, 25, 7125, 16, CURRENT_DATE + INTERVAL '18 days'),

-- ============== BABY & KIDS (9 items) ==============
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Cerelac Baby Cereal Wheat 300g', 'Nestle', 'Pantry', 'Stage 1 baby food cereal', 'https://www.bigbasket.com/media/uploads/p/l/271373_8-nestle-cerelac-baby-cereal-wheat.jpg', 21500, 20, 17200, 10, CURRENT_DATE + INTERVAL '20 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Bournvita Health Drink 500g', 'Cadbury', 'Beverages', 'Chocolate flavoured health drink for kids', 'https://www.bigbasket.com/media/uploads/p/l/266019_10-cadbury-bournvita-health-drink-chocolate.jpg', 22000, 25, 16500, 14, CURRENT_DATE + INTERVAL '15 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Complan Royale Chocolate 500g', 'Complan', 'Beverages', 'Nutrition drink for growing kids', 'https://www.bigbasket.com/media/uploads/p/l/40025215_4-complan-nutrition-health-drink-royale-chocolate.jpg', 26000, 20, 20800, 8, CURRENT_DATE + INTERVAL '18 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Horlicks Classic Malt 500g', 'Horlicks', 'Beverages', 'Health and nutrition drink', 'https://www.bigbasket.com/media/uploads/p/l/267171_8-horlicks-health-nutrition-drink-classic-malt.jpg', 24000, 20, 19200, 12, CURRENT_DATE + INTERVAL '22 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Parle Monaco Salted Biscuit 200g', 'Parle', 'Snacks', 'Classic zeera salted cracker biscuit', 'https://www.bigbasket.com/media/uploads/p/l/40020135_4-parle-monaco-classic-regular-salted-biscuit.jpg', 3500, 30, 2450, 25, CURRENT_DATE + INTERVAL '12 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Hide & Seek Chocolate Chip Cookies 200g', 'Parle', 'Snacks', 'Chocolate chip cookies', 'https://www.bigbasket.com/media/uploads/p/l/40020066_4-parle-hide-seek-chocolate-chip-cookies.jpg', 4500, 25, 3375, 18, CURRENT_DATE + INTERVAL '16 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Maggi Pasta Penne 400g', 'Maggi', 'Pantry', 'Durum wheat penne pasta', 'https://www.bigbasket.com/media/uploads/p/l/40019649_4-maggi-penne-pasta.jpg', 8500, 20, 6800, 16, CURRENT_DATE + INTERVAL '24 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Yippee Noodles Magic Masala (Pack of 6)', 'Sunfeast', 'Pantry', 'Instant noodles long and slurpy', 'https://www.bigbasket.com/media/uploads/p/l/40023810_3-sunfeast-yippee-noodles-magic-masala.jpg', 9000, 30, 6300, 20, CURRENT_DATE + INTERVAL '14 days'),
('ssssssss-ssss-ssss-ssss-ssssssssssss', 'Knorr Tomato Soup 53g', 'Knorr', 'Pantry', 'Instant classic thick tomato soup', 'https://www.bigbasket.com/media/uploads/p/l/264623_5-knorr-classic-thick-tomato-soup.jpg', 5500, 35, 3575, 22, CURRENT_DATE + INTERVAL '10 days');
